### ISSUE TITLE
FATA[0000] Couldn't list clients: json: cannot unmarshal bool into Go struct field client.fullscreen of type int

### ISSUE THREAD

**Issue by n-connect** [nwg-piotr/nwg-dock-hyprland#71]
@nwg-piotr 

Thank you for the nwg-dock!

Just compiled & built the nwg-dock-hyprland in a Debian 12 docker successfully while looking for full Debian build details for nwg-shell [#18](https://github.com/nwg-piotr/nwg-shell/discussions/18) 

When I try to run the built binary `/usr/bin/nwg-dock-hyprland` got back this output and the binary did not run:

```
INFO[0000] Neither 'nwg-drawer' nor 'nwggrid' command found, and no other launcher specified; hiding the launcher button.
INFO[0000] Using style: /home/username/.config/nwg-dock-hyprland/style.css
FATA[0000] Couldn't list clients: json: cannot unmarshal bool into Go struct field client.fullscreen of type int
```
Can you please help, what is missing after following the build instructions succcessfully and `ldd` shows no missing libs for `/usr/bin/nwg-dock-hyprland` ?

The host is Debian 12 too, running repo based/packaged hyprland 0.41.2, the `make get` output from the docker:
```
make get
go get github.com/diamondburned/gotk4-layer-shell/pkg/gtklayershell
go: downloading go1.23.0 (linux/amd64)
go: downloading github.com/diamondburned/gotk4-layer-shell/pkg v0.0.0-20240109211357-6efa9f6dc438
go: downloading github.com/diamondburned/gotk4-layer-shell v0.0.0-20240109211357-6efa9f6dc438
go: downloading github.com/diamondburned/gotk4/pkg v0.3.1
go: downloading golang.org/x/sync v0.10.0
go: downloading github.com/KarpelesLab/weak v0.1.1
go: downloading go4.org/unsafe/assume-no-moving-gc v0.0.0-20231121144256-b99613f794b6
go get github.com/diamondburned/gotk4/pkg
go: downloading github.com/diamondburned/gotk4 v0.3.1
go get github.com/joshuarubin/go-sway
go: downloading github.com/joshuarubin/go-sway v1.2.0
go: downloading github.com/joshuarubin/lifecycle v1.0.0
go: downloading go.uber.org/multierr v1.1.0
go: downloading go.uber.org/atomic v1.3.2
go get github.com/allan-simon/go-singleinstance
go: downloading github.com/allan-simon/go-singleinstance v0.0.0-20210120080615-d0997106ab37
go get "github.com/sirupsen/logrus"
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading golang.org/x/sys v0.29.0
```

Thx

**Comment by nwg-piotr** [comment]
Hi,

No idea at the moment. Could you run `nwg-dock-hyprland -debug`? Possibly it's going to tell us more.

**Comment by n-connect** [comment]
Not much more info, here you go:
```
nwg-dock-hyprland -debug
DEBU[0000] HYPRLAND_INSTANCE_SIGNATURE: '918d8340afd652b011b937d29d5eea0be08467f5_1738222084_1572932455'
DEBU[0000] hyprDir: '/run/user/1000/hypr'
INFO[0000] Neither 'nwg-drawer' nor 'nwggrid' command found, and no other launcher specified; hiding the launcher button.
INFO[0000] Using style: /home/username/.config/nwg-dock-hyprland/style.css
FATA[0000] Couldn't list clients: json: cannot unmarshal bool into Go struct field client.fullscreen of type int
```

**Comment by nwg-piotr** [comment]
May I see outputs of `hyprctl clients` and `hyprctl version` on your machine?

**Comment by n-connect** [comment]
Sure, the hyperctl is the same version as HyperLand, coming from Debian 12's package - outdated v0.41.2. In parallel trying to make the last github released Hyperland get to work with compiled aquamarine (& hyprutils, etc.) tedious... Till than, the debian packaged old version stays unfortunately.

```
hyprctl clients
Window 557b75d85790 -> How to use CMake to install - Stack Overflow — Mozilla Firefox:
        mapped: 1
        hidden: 0
        at: 3440,35
        size: 1275,685
        workspace: 1 (1)
        floating: 1
        pseudo: 0
        monitor: 0
        class: firefox-esr
        title: How to use CMake to install - Stack Overflow — Mozilla Firefox
        initialClass: firefox-esr
        initialTitle: Mozilla Firefox
        pid: 3986961
        xwayland: 0
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        tags:
        swallowing: 0
        focusHistoryID: 1

Window 557b75e81ef0 -> wezterm:
        mapped: 1
        hidden: 0
        at: 3440,35
        size: 1279,684
        workspace: 1 (1)
        floating: 1
        pseudo: 0
        monitor: 0
        class: org.wezfurlong.wezterm
        title: wezterm
        initialClass: org.wezfurlong.wezterm
        initialTitle: wezterm
        pid: 3019024
        xwayland: 1
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        tags:
        swallowing: 0
        focusHistoryID: 0
```

```
hyprctl version
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)
```
